#!/bin/bash

# Configure worktree commands for bash shell
set -e

echo "🐚 Configuring bash worktree commands..."

# Environment variables are loaded by postCreate.sh and exported to child processes

# Note: This modifies bash profile within the DevContainer environment only.
# The modifications are isolated to the container and do not affect the host system.

cd "$workingCopy"

# Check if worktree configuration already exists to prevent duplicates
if ! grep -q "Git Worktree Management - Generated by worktree.sh init for bash" ~/.bashrc 2>/dev/null; then
    echo "Adding worktree configuration to bash profile..."
    # Only redirect stdout to bashrc, let stderr go to terminal to avoid ANSI sequences in RC files
    if ./scripts/worktree/worktree.sh init --shell bash >> ~/.bashrc; then
        echo "✅ Bash worktree configuration added"
    else
        echo "⚠️ Failed to initialize worktree for bash"
        exit 1
    fi
else
    echo "✅ Bash worktree configuration already exists"
fi

cd -
echo "✅ Bash worktree configuration completed"