#!/bin/bash

# Configure worktree commands for zsh shell
set -e

echo "🐚 Configuring zsh worktree commands..."

# Environment variables are loaded by postCreate.sh and exported to child processes

# Note: This modifies zsh profile within the DevContainer environment only.
# The modifications are isolated to the container and do not affect the host system.

# Validate working copy directory and worktree script existence
if [[ -z "$workingCopy" ]]; then
    echo "⚠️ Working copy path not set, skipping zsh worktree initialization"
    exit 0
elif [[ ! -d "$workingCopy" ]]; then
    echo "⚠️ Working copy directory not found: $workingCopy, skipping zsh worktree initialization"
    exit 0
elif [[ ! -x "$workingCopy/scripts/worktree/worktree.sh" ]]; then
    echo "⚠️ Worktree script not found or not executable, skipping zsh worktree initialization"
    exit 0
fi

cd "$workingCopy"

if ! grep -q "Git Worktree Management - Generated by worktree.sh init for zsh" ~/.zshrc 2>/dev/null; then
    echo "Adding worktree configuration to zsh profile..."
    # Only redirect stdout to zshrc, let stderr go to terminal to avoid ANSI sequences in RC files
    if ./scripts/worktree/worktree.sh init --shell zsh >> ~/.zshrc; then
        echo "✅ Zsh worktree configuration added"
    else
        echo "⚠️ Failed to initialize worktree for zsh"
        exit 1
    fi
else
    echo "✅ Zsh worktree configuration already exists"
fi

cd -
echo "✅ Zsh worktree configuration completed"