#!/bin/bash

# Initialize worktree commands for both shells
set -e

echo "🔧 Initializing worktree commands..."

# Environment variables are loaded by postCreate.sh and exported to child processes

# Note: This modifies shell profiles within the DevContainer environment only.
# The modifications are isolated to the container and do not affect the host system.

# Validate working copy directory and worktree script existence
if [[ -z "$workingCopy" ]]; then
    echo "⚠️ Working copy path not set, skipping worktree initialization"
elif [[ ! -d "$workingCopy" ]]; then
    echo "⚠️ Working copy directory not found: $workingCopy, skipping worktree initialization"
elif [[ ! -x "$workingCopy/scripts/worktree/worktree.sh" ]]; then
    echo "⚠️ Worktree script not found or not executable, skipping worktree initialization"
else
    cd "$workingCopy"
    
    # Check if worktree configuration already exists to prevent duplicates
    if ! grep -q "Git Worktree Management - Generated by worktree.sh init for bash" ~/.bashrc 2>/dev/null; then
        echo "Adding worktree configuration to bash profile..."
        # Only redirect stdout to bashrc, let stderr go to terminal to avoid ANSI sequences in RC files
        if ./scripts/worktree/worktree.sh init --shell bash >> ~/.bashrc; then
            echo "✅ Bash worktree configuration added"
        else
            echo "⚠️ Failed to initialize worktree for bash"
        fi
    else
        echo "✅ Bash worktree configuration already exists"
    fi
    
    if ! grep -q "Git Worktree Management - Generated by worktree.sh init for zsh" ~/.zshrc 2>/dev/null; then
        echo "Adding worktree configuration to zsh profile..."
        # Only redirect stdout to zshrc, let stderr go to terminal to avoid ANSI sequences in RC files
        if ./scripts/worktree/worktree.sh init --shell zsh >> ~/.zshrc; then
            echo "✅ Zsh worktree configuration added"
        else
            echo "⚠️ Failed to initialize worktree for zsh"
        fi
    else
        echo "✅ Zsh worktree configuration already exists"
    fi
    
    cd -
fi

echo "✅ Worktree initialization completed"